### PR TITLE
Implement basic RESTful server

### PR DESCRIPTION
**Pull request by timofurrer**

### CODE REVIEW

**Comment by ncrocfer** [comment]
It's your turn to have conflict with @brouberol ^^ Can you fix it in `__main__.py` please ?
```python
++<<<<<<< HEAD
 +from .core import get_ports, get_dict
++=======
+ from .core import get_ports
+ from .server import app
++>>>>>>> 263b7ab6806e88de6b1384c5d2ff4c22bbf90a19
...
++<<<<<<< HEAD
 +@click.option('--json', is_flag=True, default=False,
 +              help='Format the output result as JSON.')
 +def run(port, like, json):
++=======
+ @click.option("--server", is_flag=True, default=False,
+               help="Start a RESTful server.")
+ @click.option("--server-host", default="localhost",
+               help="Hostname for the server.")
+ @click.option("--server-port", default=8080,
+               help="Port for the server.")
+ def run(port, like, server, server_host, server_port):
++>>>>>>> 263b7ab6806e88de6b1384c5d2ff4c22bbf90a19
```

By the way it's a very good and useful (I think) PR, but I have 2 comments :
- originally the tool was designed to be simple, now we have many options for a single feature, (--server, --server-host, --server-port). Can you merge it in 1 single option to have a cleaner help ?
Example : `whatportis --server 127.0.0.1 8000` instead of `whatportis --server --server-host=127.0.0.1 --server-port=8000`. It's very simple with click (http://click.pocoo.org/5/options/#multi-value-options).
- and can you update the README to inform users about this new feature please ? For example telling them how to launch the server, and 1 or 2 curl examples (`curl 127.0.0.1:8080/ports/5432`, `curl 127.0.0.1:8080/ports/mysql?like`).

Thank you :)

**Comment by timofurrer** [comment]
It's updated now ;)

**Comment by ncrocfer** [comment]
Arff, apparently `click` does not support default values for `narg > 1` (https://github.com/mitsuhiko/click/issues/472#issuecomment-160638889) !
I merge it anyway, thanks :+1:

**Comment by timofurrer** [comment]
I know - that's why I implemented it the way I did ;) :beers:

**Pull request merged**
