### PR TITLE
Add a --json flag, displaying results a pretty-printed JSON

### PR DESCRIPTION
**Pull request by brouberol**

### CODE REVIEW

**Comment by timofurrer** [comment]
Sorry @brouberol , I think my changes broke the fastforward merge of this PR.

**Comment by ncrocfer** [comment]
Thanks for this PR !

The `main.py` file has been renamed to `__main__.py` with #1, can you adapt it before merging please ?

**Comment by brouberol** [comment]
Done:

**Comment by ncrocfer** [comment]
Thanks @brouberol !

**Pull request merged**
